apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cr57ez09n-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cr57ez09n-java-quarkus-gitops